### ISSUE TITLE
Native Linking Failing for iOS

### ISSUE THREAD

**Issue by tkieronski** [dynamsoft-dbr/xamarin#1]
I get this error when taking your project and after installing nuget package I try to compile:

MTOUCH : error MT5216: Native linking failed for '/Users/tkieronski/Downloads/xamarin-master 2/examples/iOS/helloworld/DBRdemo/obj/iPhone/Debug/device-builds/iphone10.3-11.4.1/mtouch-cache/arm64/libDBRiOS.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com
Done building target "_CompileToNative" in project "DBRdemo.csproj" -- FAILED.

**Comment by tkieronski** [comment]
This does not resolve the problem now I get a bunch of errors like:


Native linking failed, undefined symbol: _CGImageGetBytesPerRow. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. | DBRdemo |

**Comment by tkieronski** [comment]
I was able to create my own project and install Dynamsoft library and that build fine - just your demo does not.

**Comment by yushulx** [comment]
@tkieronski please pull the latest code and try it again.

**Comment by tkieronski** [comment]
Thanks that now works
